on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker build -t ghcr.io/riccap/angular-test:${{ github.sha }} .

    # - docker push ghcr.io/OWNER/IMAGE_NAME:2.5
